application/models/app/Driver1_model.php
=> driver model changes

application/models/app/Driver1_model.php
home page api total booking,earnings added
=> home page api total booking,earnings added

application/controllers/app/Driver1.php, application/models/app/Driver1_model.php
=> featching current rides

application/controllers/app/Sharing.php
testing changes git - 28-11-2022
=> testing changes git

application/controllers/app/Sharing.php
=> removing-testing-code

application/controllers/app/Sharing.php
get distance api changes in sharing
=> get distance api changes in sharing

application/controllers/app/Taxi_flow.php
defalut-img-added-user_details-api
=> defalut-img-added-user_details-api

application/controllers/app/Taxi_flow.php
user-profile-changes-with-array-images
=> user-profile-changes-with-array-images

application/controllers/app/Driver1.php, application/models/app/Driver1_model.php
three-apis-added-in-driver-module
=> three-apis-added-in-driver-module

application/controllers/app/Sharing.php
rides_requested
rides_requested_later
=> rides_requested-and-rides_requested_later

application/controllers/app/Menuitems.php
=> edit-emergency-contacts

application/controllers/app/Menuitems.php
=> edit-bank-and-upi-details

application/controllers/app/Sharing.php, application/models/app/Sharing_model.php
-check_for_ongoing_ride
-order_tracking
-user_cancelled_orders
-rides_offered
-rides_offered_later
=> sharing-api-responses

application/controllers/app/Driver1.php, application/controllers/app/Sharing.php, application/helpers/app/ws_helper.php, application/models/app/Sharing_model.php
get-user-vehicles-details-added
=> get-user-vehicles-details-added

application/controllers/app/DriverMenuitems.php, application/controllers/app/Taxi_flow.php, application/models/app/DriverMenuitems_model.php
=> deiver-menu-items

application/controllers/app/Driver1.php
Complete-ride-Submit-Review-added
=> Complete-ride-Submit-Review-added

application/controllers/app/Sharing.php, application/models/app/DriverMenuitems_model.php
=> DriverController-change

.htaccess
=> htaccess issue resloved

application/controllers/app/Driver_menuitems.php
=> driver-new-controller

application/controllers/app/Driver_menuitems.php
=> driver-test-function

index.php
=> changed-developemnt-mode

application/controllers/app/Driver_menuitems.php
=> driver-model-name-change

application/models/app/DriverMenuitems_model.php
=> driver-model-test

application/controllers/app/Drivermitems.php, application/models/app/Drivermitems_model.php
driver-controller-final-controller-and-model
=> driver-controller-final-controller-and-model

application/views/admin/includes/leftside_menu.php
=> admin-menu

application/controllers/admin/Roles.php, application/models/Common_model.php, application/models/admin/Rolesmodel.php, application/views/admin/includes/leftside_menu.php, application/views/admin/roles/add_employees.php, application/views/admin/roles/add_roles.php, application/views/admin/roles/edit_employees.php, application/views/admin/roles/edit_roles.php, application/views/admin/roles/list_employees.php, application/views/admin/roles/list_roles.php, application/views/admin/roles/view_employees.php, application/views/admin/roles/view_role_emps.php, index.php
Roles and responsibilietes and api changes
=> Roles and responsibilietes and api changes

index.php
=> index.php-file-chnages

application/controllers/app/Sharing.php
check-availability-api-chnages
=> check-availability-api-chnages

application/views/admin/includes/leftside_menu.php, application/views/admin/roles/add_roles.php
=> side-menu-and-add-role-design

application/controllers/app/Drivermitems.php, application/models/app/Drivermitems_model.php
=> driver-menu-rides

application/controllers/admin/Roles.php, application/models/Common_model.php, application/models/admin/Rolesmodel.php, application/views/admin/roles/edit_roles.php
=> Roles-view-page-chnages

application/controllers/app/Drivermitems.php, application/models/app/Drivermitems_model.php
=> driver-menu-items-my-rides

application/models/app/Drivermitems_model.php
=> drive-model

application/models/app/Drivermitems_model.php
=> drive-model-change

application/controllers/admin/Roles.php, application/models/app/Drivermitems_model.php, application/views/admin/includes/leftside_menu.php, application/views/admin/roles/edit_roles.php, application/views/admin/roles/list_roles.php
Edit-role-and-list-roles-design-issues-resolved
=> Edit-role-and-list-roles-design-issues-resolved

application/controllers/admin/Roles.php, application/models/Common_model.php, application/models/admin/Rolesmodel.php, application/views/admin/includes/leftside_menu.php, application/views/admin/roles/add_employees.php, application/views/admin/roles/edit_employees.php, application/views/admin/roles/list_employees.php
=> employees-functionality-added

application/controllers/app/Taxi_flow.php
=> upload-image-api-validation

application/controllers/app/Taxi_flow.php
=> uploadfile-new-api

application/views/admin/includes/leftside_menu.php, application/views/admin/roles/add_employees.php, application/views/admin/roles/edit_employees.php, application/views/admin/roles/list_employees.php
list-employee-and-add-employee-design
=> list-employee-and-add-employee-design
